backend:
  name: git-gateaway
  space_id: ${CONTENTFUL_SPACE_ID}
  access_token: ${CONTENTFUL_DELIVERY_TOKEN}
  environment: master

media_folder: "assets/img/uploads"
public_folder: "/assets/img/uploads"

collections:
  - name: "artikel-desa"
    label: "Artikel Desa"
    folder: "content/artikel-desa"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Judul", name: "judul", widget: "string" }
      - { label: "Tanggal Upload", name: "tanggalUpload", widget: "datetime" }
      - { label: "Penulis", name: "penulis", widget: "string" }
      - { label: "Foto", name: "foto", widget: "image" }
      - { label: "Isi Artikel", name: "isiArtikel", widget: "markdown" }
