backend:
  name: git-gateway
  branch: main

media_folder: "assets/img/uploads"
public_folder: "/assets/img/uploads"

collections:
  - name: "artikel"
    label: "Artikel Petani"
    folder: "artikel"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Tanggal", name: "date", widget: "datetime" }
      - { label: "Penulis", name: "author", widget: "string" }
      - { label: "Foto", name: "image", widget: "image" }
      - { label: "Isi Artikel", name: "body", widget: "markdown" }
