backend:
  name: contentful
  space_id: ${CONTENTFUL_SPACE_ID}
  access_token: ${CONTENTFUL_ACCESS_TOKEN}
  preview_token: ${CONTENTFUL_PREVIEW_TOKEN}
  environment: master

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "artikel-desa"
    label: "Artikel Desa"
    folder: "content/artikel-desa"
    create: true
    fields:
      - { label: "Judul", name: "judul", widget: "string" }
      - { label: "Tanggal Upload", name: "tanggalUpload", widget: "datetime" }
      - { label: "Penulis", name: "penulis", widget: "string" }
      - { label: "Foto", name: "foto", widget: "image" }
      - { label: "Isi Artikel", name: "isiArtikel", widget: "markdown" }
